services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/bsp
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bsp
    depends_on:
      - db  
    networks:
      - bsp_network
    restart: on-failure

  # frontend:
  #   # image: bsp_frontend-test:latest
  #   build: ./bsp-frontend
  #   ports:
  #     - "4200:4200"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - web
  #   networks:
  #     - bsp_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bsp
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bsp_network
    command: ["postgres"]   

volumes:
  postgres_data:

networks:
  bsp_network:
    driver: bridge
